on:
  workflow_call:
    inputs:
      PACKAGE_NAME:
        required: true
        type: string
      EXISTING_TAG:
        required: true
        type: string
      APP_VERSION:
        required: true
        type: string
      AZ_REGISTRY_URL:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Remove tag if exists
    - name: Add tag to image
      run: |
        az acr import \
           --name $(echo ${{ inputs.AZ_REGISTRY_URL }} | cut -d. -f1) \
           --source ${{ inputs.AZ_REGISTRY_URL }}/${{ inputs.PACKAGE_NAME }}:${{ inputs.EXISTING_TAG }} \
           --image ${{ inputs.PACKAGE_NAME }}:${{ inputs.APP_VERSION }} \
           --force
